Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 02/10/2024
Var

numero: inteiro


Inicio

      Escreval("Digite um número:")
      leia(numero)

    Se (numero > 4) então
    
      Escreval (numero, " é MAIOR que 4")
      
    Senão
    
      Escreval(numero, " é MENOR que 4")

    fimse
Fimalgoritmo